### ISSUE TITLE
    copy i copy mujoco200 as mujoco200_linux, and there exist both mujoco200 and mujoco200_linux under ~/.mujoco/ directory.

### ISSUE THREAD

**Issue by GUESSZERO4** [rail-berkeley/offline_rl#122]
>>> import d4rl
Warning: Flow failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'flow'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lxy/d4rl/d4rl/__init__.py", line 32, in <module>
    import d4rl.kitchen
  File "/home/lxy/d4rl/d4rl/kitchen/__init__.py", line 1, in <module>
    from .kitchen_envs import KitchenMicrowaveKettleLightSliderV0, KitchenMicrowaveKettleBottomBurnerLightV0
  File "/home/lxy/d4rl/d4rl/kitchen/kitchen_envs.py", line 5, in <module>
    from d4rl.kitchen.adept_envs.franka.kitchen_multitask_v0 import KitchenTaskRelaxV1
  File "/home/lxy/d4rl/d4rl/kitchen/adept_envs/franka/kitchen_multitask_v0.py", line 23, in <module>
    from dm_control.mujoco import engine
  File "/home/lxy/anaconda3/envs/decision-transformer-gym/lib/python3.8/site-packages/dm_control/mujoco/__init__.py", line 18, in <module>
    from dm_control.mujoco.engine import action_spec
  File "/home/lxy/anaconda3/envs/decision-transformer-gym/lib/python3.8/site-packages/dm_control/mujoco/engine.py", line 42, in <module>
    from dm_control.mujoco import index
  File "/home/lxy/anaconda3/envs/decision-transformer-gym/lib/python3.8/site-packages/dm_control/mujoco/index.py", line 88, in <module>
    from dm_control.mujoco.wrapper import util
  File "/home/lxy/anaconda3/envs/decision-transformer-gym/lib/python3.8/site-packages/dm_control/mujoco/wrapper/__init__.py", line 20, in <module>
    from dm_control.mujoco.wrapper.core import callback_context
  File "/home/lxy/anaconda3/envs/decision-transformer-gym/lib/python3.8/site-packages/dm_control/mujoco/wrapper/core.py", line 29, in <module>
    from dm_control.mujoco.wrapper.mjbindings import functions
  File "/home/lxy/anaconda3/envs/decision-transformer-gym/lib/python3.8/site-packages/dm_control/mujoco/wrapper/mjbindings/functions.py", line 17, in <module>
    mjlib = util.get_mjlib()
  File "/home/lxy/anaconda3/envs/decision-transformer-gym/lib/python3.8/site-packages/dm_control/mujoco/wrapper/util.py", line 120, in get_mjlib
    return ctypes.cdll.LoadLibrary(library_path)
  File "/home/lxy/anaconda3/envs/decision-transformer-gym/lib/python3.8/ctypes/__init__.py", line 459, in LoadLibrary
    return self._dlltype(name)
  File "/home/lxy/anaconda3/envs/decision-transformer-gym/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/lxy/.mujoco/mujoco200_linux/bin/libmujoco200.so: undefined symbol: __glewBindBuffer
>>>

**Comment by lylwy** [comment]
> 

I encountered the same error and performed the same operation as you, but it didn't work.

**Comment by lylwy** [comment]
> I solved my problem by running the following command “sudo apt-get install -y libglew-dev”.

I encountered the same error and performed the same operation as you, but it didn't work.
